#!/bin/bash
# Stop Bukkit server
#
# Part of Linux Bukkit Tools
#
# Use at own risk
# 
# (c) AJ Salkeld

OPTIND=1 

while getopts "f" opt; do
    if [ "$opt" == "f" ] ; then
        echo "Forcing session to close..."
        screen -X -S bukkit quit
        echo "Done."
        exit
    fi
    if [ "$opt" == "" ]
        echo "Asking Bukkit to close..."
        screen -S bukkit -p 0 -X stuff 'stop^M'
        echo "Waiting 15 seconds..."
        sleep 15
        echo "Ensuring session is killed..."
        screen -X -S bukkit quit
        echo "Done."
        exit
    fi
done
exit