#!/bin/bash
# View Bukkit server shell
#
# Part of Linux Bukkit Tools
#
# Use at own risk
# 
# (c) AJ Salkeld

echo "Entering screen..."
echo "Exit by first pressing ctrl + a, then d."
sleep 5

screen -r bukkit

exit